import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "public/sw.js",
      // Regenerated by Next.js on every build, and its triple-slash references
      // violate a rule we want everywhere else. Linting a generated file only
      // produces an error nobody is allowed to fix.
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    // DF-SEC-028 / DF-ENG-021. The service role client bypasses row level
    // security entirely, so it is confined to the cron handlers that genuinely
    // need to act across all users. A key reaching a client bundle would expose
    // every user at once, and no behavioural test would catch it.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/app/api/cron/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/lib/supabase/admin", "@/lib/supabase/admin"],
              message:
                "The service role client bypasses RLS and may only be imported from src/app/api/cron/.",
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
